### ISSUE TITLE
Could not convert "::1@53" to an IP dict: Generic error

### ISSUE THREAD

**Issue by vollkommenheit** [getdnsapi/getdns#215]
At least with 1.1.0-alpha3, I get `Could not convert "::1@53" to an IP dict: Generic error` when running the sample command shown at https://portal.sinodun.com/wiki/display/TDNS/DNS+Privacy+daemon 

`sudo getdns_query -s @185.49.141.38 @2a04:b900:0:100::38 -l L -z 127.0.0.1@53 -z ::1@53 -e 10000`

`Could not convert "::1@53" to an IP dict: Generic error`

Using `127.0.0.1@53` alone is fine.

The same issue persists, even after manually adding "nameserver ::1" to /etc/resolv.conf.

**Comment by wtoorop** [comment]
Yes, I am aware of this.  This is because internally it is using the string to json-like format conversion.  The ':' character is a separator.

We have a similar issue with the conventional IPv6 + port syntax: [::1]:53 (which was available before), because in the json-like format this is interpreted as the start of a list.  I believe I had this fixed earlier... but lack of a proper unit test made it return.  I'll look at this shortly.

For the time being you could use 0::1@53 to specify the IPv6 localhost address.

Thanks for reporting though!

**Comment by wtoorop** [comment]
Commit bc9ebd5 deals with this.
Thanks
