### ISSUE TITLE
[getdns_query] Error messages and response codes

### ISSUE THREAD

**Issue by bortzmeyer** [getdnsapi/getdns#253]
```
% src/test/getdns_query  @2001:db8::1 -s www.bortzmeyer.org
SYNC response:
{
  "answer_type": GETDNS_NAMETYPE_DNS,
  "canonical_name": <bindata for www.bortzmeyer.org.>,
  "replies_full": [],
  "replies_tree": [],
  "status": GETDNS_RESPSTATUS_ALL_TIMEOUT
}
Response code was: GOOD. Status was: All queries for the name timed out

All done.
```

"Response code was: GOOD" for a request to a non-existing name server is strange. (The status is OK)

**Comment by wtoorop** [comment]
Yes that looks a bit silly.  But the getdns_query tool was really our private development tool we used to try out the operation of all functions while we were developing those.  The message just means that the value getdns_general_sync() returned was GETDNS_RETURN_GOOD.  Because the function could perform as intended.
Now that getdns_query becomes more prominent (especially in the form for stubby), it might be worthwhile to review all this yes.

B.t.w. Did you checkout and build from the release/1.1.0-alpha3 branch?  I has quite some improvements over the develop branch.  Especially in stub operation for DNS over TLS.

**Comment by bortzmeyer** [comment]
Yes, this was with 1.1.0-alpha3 branch.

**Comment by saradickinson** [comment]
This is related to #9

**Comment by wtoorop** [comment]
Those messages are not displayed anymore by default.
