### ISSUE TITLE
gnuTLS problems due to lack of DANE support

### ISSUE THREAD

**Issue by hanvinke** [getdnsapi/getdns#461]
While testing with gnuTLS and the newest RC (git checkout remotes/origin/release/1.6.0-rc.1) I noticed some problems with stubby. On Arch linux there is no built-in support for DANE. With 'stubby -'i or 'stubby --version' you get the following error:
'stubby: error while loading shared libraries: libgnutls-dane.so.0: cannot open shared object file: No such file or directory'
This is of course due to the missing libraries. You need gnutls-dane. But those packages are only available in a number of distributions. Ubuntu and Open-Suse have no problems. But Arch doesn't have any package, not even in the AUR.
Currently gnutls is compiled without DANE support. The manual says: 

"Since the DANE library is not included in GnuTLS it requires programs to be linked against it. This can be achieved with the following commands.
gcc -o foo foo.c `pkg-config gnutls-dane --cflags --libs`.

Is it possible to tell which files exactly have to be patched for this?

PS 'Unbound' is installed

**Comment by banburybill** [comment]
The shard library error - I'm guessing this is produced when you copy an executable compiled on a non-Arch system onto an Arch system? And for context, can you point me to the manual from which you took that extract?

But unless I'm missing something, that command line requires the `gnutls-dane` library to be present on the building system, and the problem here is that on Arch it isn't. Right now, using GnuTLS with getdns requires the GnuTLS DANE library; it's not optional. The only way to include it would be to compile stubby on a system with GnuTLS DANE installed, but link statically. I guess what I'm asking here is what exactly you're trying to do.

**Comment by hanvinke** [comment]
Hi, thank you. The shared library error just happens when I type 'stubby -i' in a terminal on Arch. 
Normally I get info, but now just this error message. Stubby is BTW running fine for the rest.

The info is from 'https://www.gnutls.org/manual/html_node/Certificate-verification.html#Certificate-verification'. It is not much information, and unclear to me.

When building gnuTLS there might be another switch needed for configuring: '--enable-libdane'. I will check that tomorrow. Maybe there is also an unbound dependancy?

**Comment by hanvinke** [comment]
Today I did a timeshift and repeated the steps again. All went well and: 'whereis libgnutls-dane.so.0
libgnutls-dane.so: /usr/lib/libgnutls-dane.so.0 /usr/lib/libgnutls-dane.so'.
So the library has been found. I compiled gnuTLS also with the switch  '--enable-libdane'. Unfortunately I don't know if that did the trick or something else. Well at least I can close the ticket now. Thanks banburybill.
